[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']
aptPkgs = []

[phases.install]
cmds = ['npm ci --include=dev']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npm run migrate:deploy && npm run start:prod'
