[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run migrate:deploy && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/api/docs"
timeout = 300
