[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npm run migrate:deploy && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
